config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "stations/suggests", to: "stations#suggests", defaults: { format: 'json' }
  get "stations/search", to: "stations#search", defaults: { format: 'json' }
  resources :stations
  root 'stations#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/station.rb
class Station < ApplicationRecord
	validates :number, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  # => require 'rio_station_service'
  before_action :set_station, only: [:show, :edit, :update, :destroy]

  def suggests
    if [:q, :street, :city].any? {|k| params.key? k}
      request_params = {
        limit:  10,
        city: "Rio de Janeiro",
        state: "RJ",
        country: "Brasil"
      }

      request_params[:q] = params[:q] if params.has_key?(:q)
      request_params[:street] = params[:street] if params.has_key?(:street)
      request_params[:city] = params[:city] if params.has_key?(:city)

      result = OpenStreetMapService.get(request_params).map do |data|
        {
          lat: data["lat"],
          lon: data["lon"],
          street: data["address"]["road"],
          suburb: data["address"]["suburb"],
          city_district: data["address"]["city_district"],
          city: data["address"]["city"],
          state: data["address"]["state"],
          country: data["address"]["country"]
        }
      end
      respond_to do |format|
        format.json { render :json => result }
      end
    end
  end

  def search
    @stations = Station.all
    result = nil

    # when will check new stations?
    if @stations.empty?
      get_station
      @stations = Station.all
    end

    if params.has_key?(:lat) && params.has_key?(:lon)
      lat = params[:lat].to_f
      lon = params[:lon].to_f
      result = @stations.all.map do |s|
        {
          station: s.attributes,
          distance: Math.sqrt((s[:latitude] - lat)**2 + (s[:longitude] - lon)**2)
        }
      end
      result = result.min { |a,b| a[:distance] <=> b[:distance] }

    end
    respond_to do |format|
      format.json { render :json => result }
    end
  end

  # GET /stations
  # GET /stations.json
  def index
    @stations = Station.all
    if(@stations.empty?)
      get_station
      @stations = Station.all
    end
    gon.stations = @stations
    gon.your_int = 1
  end


  # GET /stations/1
  # GET /stations/1.json
  def show
  end

  # GET /stations/new
  def new
    @station = Station.new
  end

  # GET /stations/1/edit
  def edit
  end

  # POST /stations
  # POST /stations.json
  def create
    @station = Station.new(station_params)

    respond_to do |format|
      if @station.save
        format.html { redirect_to @station, notice: 'Station was successfully created.' }
        format.json { render :show, status: :created, location: @station }
      else
        format.html { render :new }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stations/1
  # PATCH/PUT /stations/1.json
  def update
    respond_to do |format|
      if @station.update(station_params)
        format.html { redirect_to @station, notice: 'Station was successfully updated.' }
        format.json { render :show, status: :ok, location: @station }
      else
        format.html { render :edit }
        format.json { render json: @station.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stations/1
  # DELETE /stations/1.json
  def destroy
    @station.destroy
    respond_to do |format|
      format.html { redirect_to stations_url, notice: 'Station was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def station_params
      params.require(:station).permit(:neighborhood, :station, :code, :address, :number, :latitude, :longitude)
    end

    def get_station
      stations = RioStationService.get
      columns  = stations["COLUMNS"].map {|c| RioStationService.DICTIONARY[c] }
      data     = stations["DATA"]
      if (columns - Station.column_names).empty?
        for d in data
          d = d.map do |i|
            if(i.class == String)
              i.force_encoding("ISO-8859-1").encode("UTF-8")
            else
              i
            end
          end
          Station.create(columns.each_with_index.map {|c,i| [c,d[i]] }.to_h)
        end
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>STIDesafio02</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  	<%= javascript_pack_tag 'application' %>
    <%= include_gon %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/stations/_form.html.erb
<%= form_with(model: station, local: true) do |form| %>
  <% if station.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(station.errors.count, "error") %> prohibited this station from being saved:</h2>

      <ul>
      <% station.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :neighborhood %>
    <%= form.text_field :neighborhood, id: :station_neighborhood %>
  </div>

  <div class="field">
    <%= form.label :station %>
    <%= form.text_field :station, id: :station_station %>
  </div>

  <div class="field">
    <%= form.label :code %>
    <%= form.number_field :code, id: :station_code %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :station_address %>
  </div>

  <div class="field">
    <%= form.label :number %>
    <%= form.number_field :number, id: :station_number %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :station_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :station_longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stations/edit.html.erb
<h1>Editing Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Show', @station %> |
<%= link_to 'Back', stations_path %>

app/views/stations/index.html.erb
<p id="notice"><%= notice %></p>

<div>
  <span >Informe seu endereço para saber qual a estação de BikeRio mais próxima: </span>
  <div ><%= react_component("SuggestBar") %> </div>
</div>
<%= react_component("StationsTable", {stations: @stations}) %>


<br>

<%= link_to 'New Station', new_station_path %>

app/views/stations/new.html.erb
<h1>New Station</h1>

<%= render 'form', station: @station %>

<%= link_to 'Back', stations_path %>

app/views/stations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Neighborhood:</strong>
  <%= @station.neighborhood %>
</p>

<p>
  <strong>Station:</strong>
  <%= @station.station %>
</p>

<p>
  <strong>Code:</strong>
  <%= @station.code %>
</p>

<p>
  <strong>Address:</strong>
  <%= @station.address %>
</p>

<p>
  <strong>Number:</strong>
  <%= @station.number %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @station.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @station.longitude %>
</p>

<%= link_to 'Edit', edit_station_path(@station) %> |
<%= link_to 'Back', stations_path %>